In [1]:
import numpy as np

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [16]:
import numpy as np
Array=np.array([[[[1,2,3,4],[5,10,15,20],[10,20,30,40],[1,2,3,4]]]])
print(Array)
Array.ndim

[[[[ 1  2  3  4]
   [ 5 10 15 20]
   [10 20 30 40]
   [ 1  2  3  4]]]]


4

In [102]:
# find the  dimension of the array

import numpy as np
a=np.array([1,2,3,4])
print("The list is :\n",a)
print("Array dimension is :",a.ndim)
b=np.array([[1,2,3,4],[1,2,3,4]])
print("\nThe list is :\n",b)
print("Array dimension is :",b.ndim)
c=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print("\nThe list is :\n",c)
print("Array dimension is :",c.ndim)
d=np.array([[[[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]]]])
print("\nThe list is :\n",d)
print("Array dimension is :",d.ndim)

The list is :
 [1 2 3 4]
Array dimension is : 1

The list is :
 [[1 2 3 4]
 [1 2 3 4]]
Array dimension is : 2

The list is :
 [[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
Array dimension is : 3

The list is :
 [[[[1 2 3 4]
   [1 2 3 4]
   [1 2 3 4]
   [1 2 3 4]]]]
Array dimension is : 4


In [86]:
import numpy as np
b=np.array([1,2,3,4,5])
c=0
for i in range(len(b)):
    c+=b[i]
print("The sum of the elements in the array is :",c)

The sum of the elements in the array is : 15


In [88]:
# Sum the elements at the specific position

import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
c=0
for i in range(len(a)):
    c+=a[i,2]
print("The sum of the elements at the index 2 is:",c)

The sum of the elements at the index 2 is: 36


In [36]:
a[0,0,0]

5

In [98]:
# Sum the elements in 2d array at the index 0
a = np.array(
    [
    [ [1,2,3,4], [5,6,7,8], [9,10,11,12] ],  
    [ [1,2,3,4], [5,6,7,8], [9,10,11,12] ],  
    ]
)
c=0
for i in range(4):
    c+=a[0,0,i]+a[1,0,i]
print("The Sum of elements in 2d array at the index 0 is :",c)



The Sum of elements in 2d array at the index 0 is : 20


In [53]:
a = np.array(
    [1,2,3,4,5,6,7,8,9,10,11,12]
)
print(a[::2])

[ 1  3  5  7  9 11]


In [97]:
# to print the array elements in the range

a = np.array(
    [1,2,3,4,5,6,7,8,9,10,11,12]
)
print("The  elements from 1-4  :",a[:4])  # print the first 4 elements
print("The  elements from 1-10 :",a[:10]) # to print from 1-10 in the array
print("The elements from 4-10  :",a[3:10]) # print the elements from 4-10
print("The next by next elements:",a[::2])  # to print the next by next elements
print("The elements from 4-10 using negative value  :",a[-9:10]) # print the elements from 4-10 using an a negative value

The  elements from 1-4  : [1 2 3 4]
The  elements from 1-10 : [ 1  2  3  4  5  6  7  8  9 10]
The elements from 4-10  : [ 4  5  6  7  8  9 10]
The next by next elements: [ 1  3  5  7  9 11]
The elements from 4-10 using negative value  : [ 4  5  6  7  8  9 10]


In [92]:
# reshape -array
a = np.array(
    [1,2,3,4,5,6,7,8,9,10,11,12]
)
b=a.reshape(4,3)
print("The reshaped array is:\n\n",b)

The reshaped array is:

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [101]:
# concatenate -2d array
a=np.array([[10,20,30,40],[10,20,30,40]])
b=np.array([[10,20,30,40],[10,20,30,40]])
c=np.concatenate([a,b])
print("The concatenated 2d-array is :\n\n",c)

The concatenated 2d-array is :

 [[10 20 30 40]
 [10 20 30 40]
 [10 20 30 40]
 [10 20 30 40]]


In [100]:
# concatenate -1d array

a=np.array([10,20,30,40])
b=np.array([10,20,30,40])
c=np.concatenate([a,b])
print("The concatenated 1d-array is :",c)

The concatenated 1d-array is : [10 20 30 40 10 20 30 40]


In [8]:
# convert 1d array into 2d array using of reshape and find the sum of the elements in the array 

import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a1=np.array_split(a,3)
print("The splited array :\n\n",a1)
b=a.reshape(3,4)
print("\nThe reshaped array :\n",b)
c=b.reshape(2,6)
print("\nThe reshaped 2d array from 1d array is :\n",c)
d=0
for i in range(len(c[0])):
    d+=c[0,i]+c[1,i];
print("\nThe sum of the elements in the array is :",d)

The splited array :

 [array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

The reshaped array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

The reshaped 2d array from 1d array is :
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

The sum of the elements in the array is : 78


In [11]:
# create the  3d array 

import numpy as np
a=np.array(
    [[[
        [[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15]
    ]]]

)
print("The dimension of the array is :",a.ndim)

print("\nThe array list is :\n",a)

The dimension of the array is : 3

The array list is :
 [[[list([[1, 2, 3, 4], [5, 6, 7, 8]])
   list([[9, 10, 11, 12], [13, 14, 15, 16]]) list([1, 2, 3, 4])
   list([5, 6, 7, 8]) list([9, 10, 11, 12]) list([13, 14, 15])]]]


C:\Users\gdine\AppData\Local\Temp\ipykernel_19016\1413138145.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.array(
